[2016-09-09 01:28:38 043] [警告]: 打开数据库连接失败
[2016-09-09 01:28:38 043] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:28:38 402] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:28:38 433] [警告]: 获取工程路径出错
[2016-09-09 01:28:45 531] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:30:03 179] [警告]: 打开数据库连接失败
[2016-09-09 01:30:03 179] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:30:03 241] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:30:03 241] [警告]: 获取工程路径出错
[2016-09-09 01:30:03 273] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:33:28 017] [警告]: 打开数据库连接失败
[2016-09-09 01:33:28 017] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:33:28 064] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:33:28 064] [警告]: 获取工程路径出错
[2016-09-09 01:33:28 095] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:33:49 717] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:33:57 125] [警告]: 打开数据库连接失败
[2016-09-09 01:33:57 141] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:33:57 172] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:33:57 172] [警告]: 获取工程路径出错
[2016-09-09 01:33:57 265] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:34:30 993] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:35:24 690] [警告]: 打开数据库连接失败
[2016-09-09 01:35:24 690] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:35:24 706] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:35:24 737] [警告]: 获取工程路径出错
[2016-09-09 01:35:24 784] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:35:56 862] [警告]: 打开数据库连接失败
[2016-09-09 01:35:56 940] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:35:57 033] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:35:57 127] [警告]: 获取工程路径出错
[2016-09-09 01:35:57 205] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:36:10 917] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:36:16 898] [警告]: 打开数据库连接失败
[2016-09-09 01:36:16 914] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:36:16 929] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:36:16 929] [警告]: 获取工程路径出错
[2016-09-09 01:36:16 961] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:36:53 589] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:37:17 247] [警告]: 打开数据库连接失败
[2016-09-09 01:37:17 294] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:37:17 388] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:37:17 403] [警告]: 获取工程路径出错
[2016-09-09 01:37:17 575] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:38:45 158] [警告]: 打开数据库连接失败
[2016-09-09 01:38:45 158] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:38:45 173] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:38:45 189] [警告]: 获取工程路径出错
[2016-09-09 01:38:45 220] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:39:26 732] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:40:35 002] [警告]: 打开数据库连接失败
[2016-09-09 01:40:35 018] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:40:35 112] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:40:35 190] [警告]: 获取工程路径出错
[2016-09-09 01:40:35 205] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:40:57 498] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:41:12 588] [警告]: 打开数据库连接失败
[2016-09-09 01:41:12 588] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:41:12 603] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:41:12 603] [警告]: 获取工程路径出错
[2016-09-09 01:41:12 712] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:41:57 266] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:42:40 272] [警告]: 打开数据库连接失败
[2016-09-09 01:42:40 319] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:42:40 444] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:42:40 475] [警告]: 获取工程路径出错
[2016-09-09 01:42:40 506] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:45:24 598] [警告]: 打开数据库连接失败
[2016-09-09 01:45:24 645] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:45:24 707] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:45:24 707] [警告]: 获取工程路径出错
[2016-09-09 01:45:26 283] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:46:02 709] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:46:16 570] [警告]: 打开数据库连接失败
[2016-09-09 01:46:16 617] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:46:16 695] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:46:16 711] [警告]: 获取工程路径出错
[2016-09-09 01:46:16 789] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:46:32 451] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:47:48 256] [警告]: 打开数据库连接失败
[2016-09-09 01:47:48 256] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:47:48 287] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:47:48 287] [警告]: 获取工程路径出错
[2016-09-09 01:47:51 158] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:49:55 667] [警告]: 打开数据库连接失败
[2016-09-09 01:49:55 677] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:49:55 692] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:49:55 693] [警告]: 获取工程路径出错
[2016-09-09 01:49:55 733] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:50:15 846] [警告]: 打开数据库连接失败
[2016-09-09 01:50:15 853] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:50:15 873] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:50:15 874] [警告]: 获取工程路径出错
[2016-09-09 01:50:15 911] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:50:40 145] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:52:45 687] [警告]: 打开数据库连接失败
[2016-09-09 01:52:45 697] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:52:45 711] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:52:45 713] [警告]: 获取工程路径出错
[2016-09-09 01:52:45 754] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:53:54 056] [警告]: 打开数据库连接失败
[2016-09-09 01:53:54 056] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:53:54 072] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:53:54 087] [警告]: 获取工程路径出错
[2016-09-09 01:53:54 118] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:54:22 089] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:54:27 955] [警告]: 打开数据库连接失败
[2016-09-09 01:54:27 955] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:54:27 971] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:54:27 971] [警告]: 获取工程路径出错
[2016-09-09 01:54:28 017] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:54:40 341] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:55:09 057] [警告]: 打开数据库连接失败
[2016-09-09 01:55:09 065] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:55:09 077] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:55:09 087] [警告]: 获取工程路径出错
[2016-09-09 01:55:09 116] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 01:57:28 112] [警告]: 打开数据库连接失败
[2016-09-09 01:57:28 128] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 01:57:28 143] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 01:57:28 143] [警告]: 获取工程路径出错
[2016-09-09 01:57:28 174] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:04:01 810] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:04:27 036] [警告]: 打开数据库连接失败
[2016-09-09 02:04:27 052] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 02:04:27 067] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 02:04:27 070] [警告]: 获取工程路径出错
[2016-09-09 02:04:27 154] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:04:36 661] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:05:05 607] [警告]: 打开数据库连接失败
[2016-09-09 02:05:05 607] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 02:05:05 623] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 02:05:05 670] [警告]: 获取工程路径出错
[2016-09-09 02:05:05 873] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:07:16 440] [警告]: 打开数据库连接失败
[2016-09-09 02:07:16 440] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 02:07:16 502] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 02:07:16 502] [警告]: 获取工程路径出错
[2016-09-09 02:07:16 596] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:08:09 043] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:08:41 771] [警告]: 打开数据库连接失败
[2016-09-09 02:08:41 784] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 02:08:41 799] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 02:08:41 807] [警告]: 获取工程路径出错
[2016-09-09 02:08:41 876] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:10:27 468] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:10:47 597] [警告]: 打开数据库连接失败
[2016-09-09 02:10:47 628] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 02:10:47 690] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 02:10:47 706] [警告]: 获取工程路径出错
[2016-09-09 02:10:47 800] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:13:09 245] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:14:00 867] [警告]: 打开数据库连接失败
[2016-09-09 02:14:00 882] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 02:14:00 991] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 02:14:01 023] [警告]: 获取工程路径出错
[2016-09-09 02:14:01 132] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:14:08 292] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:15:12 923] [警告]: 打开数据库连接失败
[2016-09-09 02:15:12 954] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 02:15:12 954] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 02:15:12 969] [警告]: 获取工程路径出错
[2016-09-09 02:15:13 110] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:15:34 139] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:16:32 202] [警告]: 打开数据库连接失败
[2016-09-09 02:16:32 280] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 02:16:32 358] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 02:16:32 374] [警告]: 获取工程路径出错
[2016-09-09 02:16:32 483] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:18:04 647] [警告]: 打开数据库连接失败
[2016-09-09 02:18:04 740] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 02:18:04 849] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 02:18:04 849] [警告]: 获取工程路径出错
[2016-09-09 02:18:05 068] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:18:17 985] [信息]: 页[AAAA] 创建成功!
[2016-09-09 02:24:27 735] [警告]: 打开数据库连接失败
[2016-09-09 02:24:27 751] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 02:24:27 798] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 02:24:27 985] [警告]: 获取工程路径出错
[2016-09-09 02:24:28 125] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:24:38 936] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:32:00 147] [警告]: 打开数据库连接失败
[2016-09-09 02:32:00 147] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 02:32:00 163] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 02:32:00 163] [警告]: 获取工程路径出错
[2016-09-09 02:32:00 256] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:32:20 989] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:32:49 781] [警告]: 打开数据库连接失败
[2016-09-09 02:32:49 843] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 02:32:49 890] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 02:32:49 921] [警告]: 获取工程路径出错
[2016-09-09 02:32:49 983] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:33:06 722] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:33:50 726] [警告]: 打开数据库连接失败
[2016-09-09 02:33:50 740] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 02:33:50 769] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 02:33:50 771] [警告]: 获取工程路径出错
[2016-09-09 02:33:50 835] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:34:11 829] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:34:48 142] [警告]: 打开数据库连接失败
[2016-09-09 02:34:48 158] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 02:34:48 174] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 02:34:48 205] [警告]: 获取工程路径出错
[2016-09-09 02:34:48 439] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:39:08 290] [警告]: 打开数据库连接失败
[2016-09-09 02:39:08 300] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 02:39:08 316] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 02:39:08 318] [警告]: 获取工程路径出错
[2016-09-09 02:39:08 382] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:40:22 356] [警告]: 打开数据库连接失败
[2016-09-09 02:40:22 371] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 02:40:22 371] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 02:40:22 496] [警告]: 获取工程路径出错
[2016-09-09 02:40:22 668] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:51:15 450] [警告]: 打开数据库连接失败
[2016-09-09 02:51:15 450] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 02:51:15 466] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 02:51:15 466] [警告]: 获取工程路径出错
[2016-09-09 02:51:15 534] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:51:49 437] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:54:27 294] [警告]: 打开数据库连接失败
[2016-09-09 02:54:27 306] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 02:54:27 325] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 02:54:27 332] [警告]: 获取工程路径出错
[2016-09-09 02:54:27 409] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:54:40 304] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:54:53 756] [警告]: 打开数据库连接失败
[2016-09-09 02:54:53 756] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 02:54:53 823] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 02:54:53 824] [警告]: 获取工程路径出错
[2016-09-09 02:54:53 886] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:55:16 829] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:57:01 900] [警告]: 打开数据库连接失败
[2016-09-09 02:57:01 906] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 02:57:01 918] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 02:57:01 919] [警告]: 获取工程路径出错
[2016-09-09 02:57:01 983] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:58:27 461] [警告]: 打开数据库连接失败
[2016-09-09 02:58:27 469] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 02:58:27 493] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 02:58:27 494] [警告]: 获取工程路径出错
[2016-09-09 02:58:27 544] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 02:58:39 174] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:01:34 653] [警告]: 打开数据库连接失败
[2016-09-09 03:01:34 668] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 03:01:34 668] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 03:01:34 684] [警告]: 获取工程路径出错
[2016-09-09 03:01:34 749] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:03:00 046] [警告]: 打开数据库连接失败
[2016-09-09 03:03:00 049] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 03:03:00 064] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 03:03:00 064] [警告]: 获取工程路径出错
[2016-09-09 03:03:00 137] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:03:57 732] [警告]: 打开数据库连接失败
[2016-09-09 03:03:57 738] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 03:03:57 752] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 03:03:57 758] [警告]: 获取工程路径出错
[2016-09-09 03:03:57 827] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:04:40 861] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:04:56 966] [警告]: 打开数据库连接失败
[2016-09-09 03:04:56 973] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 03:04:56 989] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 03:04:56 991] [警告]: 获取工程路径出错
[2016-09-09 03:04:57 055] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:05:59 604] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:12:24 087] [警告]: 打开数据库连接失败
[2016-09-09 03:12:24 143] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 03:12:24 217] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 03:12:24 235] [警告]: 获取工程路径出错
[2016-09-09 03:12:24 301] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:15:38 314] [警告]: 打开数据库连接失败
[2016-09-09 03:15:38 322] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 03:15:38 329] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 03:15:38 329] [警告]: 获取工程路径出错
[2016-09-09 03:15:38 391] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:17:12 889] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:18:35 484] [警告]: 打开数据库连接失败
[2016-09-09 03:18:35 487] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 03:18:35 502] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 03:18:35 502] [警告]: 获取工程路径出错
[2016-09-09 03:18:35 552] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:21:35 956] [警告]: 打开数据库连接失败
[2016-09-09 03:21:35 965] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 03:21:35 982] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 03:21:35 984] [警告]: 获取工程路径出错
[2016-09-09 03:21:36 049] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:21:56 091] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:21:59 190] [警告]: 打开数据库连接失败
[2016-09-09 03:21:59 206] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 03:21:59 221] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 03:21:59 221] [警告]: 获取工程路径出错
[2016-09-09 03:21:59 258] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:22:13 859] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:22:17 558] [警告]: 打开数据库连接失败
[2016-09-09 03:22:17 574] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 03:22:17 589] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 03:22:17 605] [警告]: 获取工程路径出错
[2016-09-09 03:22:17 641] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:22:24 558] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:22:27 556] [警告]: 打开数据库连接失败
[2016-09-09 03:22:27 649] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 03:22:27 689] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 03:22:27 689] [警告]: 获取工程路径出错
[2016-09-09 03:22:27 737] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:22:37 721] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:22:40 871] [警告]: 打开数据库连接失败
[2016-09-09 03:22:40 889] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 03:22:40 905] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 03:22:40 905] [警告]: 获取工程路径出错
[2016-09-09 03:22:40 943] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:23:01 050] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:31:25 523] [警告]: 打开数据库连接失败
[2016-09-09 03:31:25 547] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-09 03:31:25 560] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-09 03:31:25 561] [警告]: 获取工程路径出错
[2016-09-09 03:31:25 595] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-09 03:49:02 854] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
