[2016-09-08 06:09:30 189] [警告]: 打开数据库连接失败
[2016-09-08 06:09:30 204] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 06:09:30 236] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 06:09:30 236] [警告]: 获取工程路径出错
[2016-09-08 06:09:30 236] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 06:09:35 887] [信息]: 页[Main] 创建成功!
[2016-09-08 06:13:57 931] [警告]: 打开数据库连接失败
[2016-09-08 06:13:57 962] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 06:13:58 087] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 06:13:58 103] [警告]: 获取工程路径出错
[2016-09-08 06:13:58 212] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 06:15:05 587] [警告]: 打开数据库连接失败
[2016-09-08 06:15:05 697] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 06:15:05 697] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 06:15:05 712] [警告]: 获取工程路径出错
[2016-09-08 06:15:05 759] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 06:16:07 961] [警告]: 打开数据库连接失败
[2016-09-08 06:16:07 972] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 06:16:07 996] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 06:16:07 999] [警告]: 获取工程路径出错
[2016-09-08 06:16:11 490] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 06:16:47 368] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 06:17:00 473] [警告]: 打开数据库连接失败
[2016-09-08 06:17:00 551] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 06:17:00 567] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 06:17:00 567] [警告]: 获取工程路径出错
[2016-09-08 06:17:00 738] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 06:17:48 288] [警告]: 打开数据库连接失败
[2016-09-08 06:17:48 304] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 06:17:48 399] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 06:17:48 399] [警告]: 获取工程路径出错
[2016-09-08 06:17:48 430] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 06:19:07 098] [警告]: 打开数据库连接失败
[2016-09-08 06:19:07 130] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 06:19:07 176] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 06:19:07 208] [警告]: 获取工程路径出错
[2016-09-08 06:19:31 110] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 06:19:36 230] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 06:20:17 419] [警告]: 打开数据库连接失败
[2016-09-08 06:20:17 434] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 06:20:17 606] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 06:20:17 606] [警告]: 获取工程路径出错
[2016-09-08 06:21:05 048] [警告]: 打开数据库连接失败
[2016-09-08 06:21:05 064] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 06:21:05 080] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 06:21:05 080] [警告]: 获取工程路径出错
[2016-09-08 06:21:09 348] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 06:22:29 453] [警告]: 打开数据库连接失败
[2016-09-08 06:22:29 464] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 06:22:29 480] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 06:22:29 489] [警告]: 获取工程路径出错
[2016-09-08 06:22:49 669] [警告]: 打开数据库连接失败
[2016-09-08 06:22:49 683] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 06:22:49 697] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 06:22:49 698] [警告]: 获取工程路径出错
[2016-09-08 06:23:44 500] [警告]: 打开数据库连接失败
[2016-09-08 06:23:44 508] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 06:23:44 524] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 06:23:44 525] [警告]: 获取工程路径出错
[2016-09-08 06:23:55 407] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 06:27:24 430] [警告]: 打开数据库连接失败
[2016-09-08 06:27:24 446] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 06:27:24 711] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 06:27:24 711] [警告]: 获取工程路径出错
[2016-09-08 06:27:24 742] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 06:27:46 780] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 07:35:54 550] [警告]: 打开数据库连接失败
[2016-09-08 07:35:54 560] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 07:35:54 710] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 07:35:54 767] [警告]: 获取工程路径出错
[2016-09-08 07:35:54 827] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 07:39:32 912] [警告]: 打开数据库连接失败
[2016-09-08 07:39:32 922] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 07:39:32 945] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 07:39:32 945] [警告]: 获取工程路径出错
[2016-09-08 07:39:32 985] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 07:40:58 544] [警告]: 打开数据库连接失败
[2016-09-08 07:40:58 554] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 07:40:58 694] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 07:40:58 704] [警告]: 获取工程路径出错
[2016-09-08 07:40:58 736] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 07:41:28 525] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 07:41:37 383] [警告]: 打开数据库连接失败
[2016-09-08 07:41:37 463] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 07:41:37 473] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 07:41:37 483] [警告]: 获取工程路径出错
[2016-09-08 07:41:37 513] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 07:43:40 043] [警告]: 打开数据库连接失败
[2016-09-08 07:43:40 056] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 07:43:40 106] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 07:43:40 106] [警告]: 获取工程路径出错
[2016-09-08 07:43:40 136] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 07:43:52 633] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 07:44:10 294] [警告]: 打开数据库连接失败
[2016-09-08 07:44:10 304] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 07:44:10 434] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 07:44:10 434] [警告]: 获取工程路径出错
[2016-09-08 07:44:10 497] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 07:44:48 557] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 07:45:38 620] [警告]: 打开数据库连接失败
[2016-09-08 07:45:38 640] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 07:45:38 650] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 07:45:38 650] [警告]: 获取工程路径出错
[2016-09-08 07:45:53 628] [警告]: 打开数据库连接失败
[2016-09-08 07:45:53 628] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 07:45:53 648] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 07:45:53 648] [警告]: 获取工程路径出错
[2016-09-08 07:45:53 678] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 07:46:46 320] [警告]: 打开数据库连接失败
[2016-09-08 07:46:46 360] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 07:46:46 390] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 07:46:46 390] [警告]: 获取工程路径出错
[2016-09-08 07:46:46 419] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 08:10:04 826] [警告]: 打开数据库连接失败
[2016-09-08 08:10:04 836] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 08:10:04 846] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 08:10:04 868] [警告]: 获取工程路径出错
[2016-09-08 08:10:04 888] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 08:11:01 144] [警告]: 打开数据库连接失败
[2016-09-08 08:11:01 152] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 08:11:01 169] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 08:11:01 171] [警告]: 获取工程路径出错
[2016-09-08 08:11:01 200] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 08:15:23 243] [警告]: 打开数据库连接失败
[2016-09-08 08:15:23 253] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 08:15:23 325] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 08:15:23 365] [警告]: 获取工程路径出错
[2016-09-08 08:15:24 354] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 08:16:01 296] [警告]: 打开数据库连接失败
[2016-09-08 08:16:01 306] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 08:16:01 316] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 08:16:01 376] [警告]: 获取工程路径出错
[2016-09-08 08:16:05 043] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 08:16:19 658] [警告]: 打开数据库连接失败
[2016-09-08 08:16:19 668] [异常]: 异常类型:MySql.Data.MySqlClient.MySqlException Unable to connect to any of the specified MySQL hosts.
	   在 MySql.Data.MySqlClient.NativeDriver.Open()
   在 MySql.Data.MySqlClient.Driver.Open()
   在 MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   在 MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   在 MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   在 MySql.Data.MySqlClient.MySqlPool.GetConnection()
   在 MySql.Data.MySqlClient.MySqlConnection.Open()
   在 SVCore.SVSqlDataBase.connect(String ip, String database, String user, String passwd, String charset) 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 40
[2016-09-08 08:16:19 718] [异常]: 异常类型:System.InvalidOperationException Connection must be valid and open.
	   在 MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   在 MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   在 MySql.Data.MySqlClient.MySqlCommand.CheckState()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   在 SVCore.SVSqlDataBase.getProPath() 位置 F:\SVDU - 新版本\SvduPro\SVCore\SVSqlDataBase.cs:行号 67
[2016-09-08 08:16:19 718] [警告]: 获取工程路径出错
[2016-09-08 08:16:21 229] [信息]: 打开工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
[2016-09-08 08:16:37 807] [信息]: 关闭工程: [F:\SVDU - 新版本\SvduPro\SvduPro\bin\Debug\TestVPro\TestVPro.svduproj]
